"""account verified new and role and status

Revision ID: 06f096604124
Revises: 15689d7d3191
Create Date: 2026-09-11 15:29:02.083842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06f096604124'
down_revision: Union[str, Sequence[str], None] = '15689d7d3191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'account_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
