"""account verified new

Revision ID: 20ce7dcf7b8c
Revises: 93639479d26b
Create Date: 2026-09-11 15:24:27.505950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20ce7dcf7b8c'
down_revision: Union[str, Sequence[str], None] = '93639479d26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_verified', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'acccount_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('acccount_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'account_verified')
    # ### end Alembic commands ###
