"""terms of services and version

Revision ID: d17f0d0a90f3
Revises: d790d96dbb35
Create Date: 2026-09-08 12:15:22.940691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd17f0d0a90f3'
down_revision: Union[str, Sequence[str], None] = 'd790d96dbb35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('terms_accepted', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('terms_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'terms_version')
    op.drop_column('users', 'terms_accepted')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
