"""account verified new and role

Revision ID: 15689d7d3191
Revises: 20ce7dcf7b8c
Create Date: 2026-09-11 15:25:45.715965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15689d7d3191'
down_revision: Union[str, Sequence[str], None] = '20ce7dcf7b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('DISPATCHER', 'VENDOR', 'ADMIN', 'USER', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('DISPATCHER', 'VENDOR', 'ADMIN', 'USER', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
